const ActionType = {
    LOAD_ACCOUNT: "LOAD_ACCOUNT",
    UPDATE_INVESTMENT_BALANCE: "UPDATE_INVESTMENT_BALANCE",
    POST_INVESTMENT: "POST_INVESTMENT",
    LOAD_REFERRAL: "LOAD_REFERRAL"
}

export default ActionType;